feat: adapt to latest utils (#153)
The latest changes in anemoi-utils made a bug in anemoi-registry
surface. Symptom is than any call to anemoi-registry cli fails with:

```
File ".../anemoi-utils/src/anemoi/utils/cli.py", line 102, in make_parser
      name, aliases=command.aliases, description=command.__doc__, help=command.__doc__
            ^^^^^^^^^^^^^^^
AttributeError: 'Download' object has no attribute 'aliases'
```

This fixes the issue.

***As a contributor to the Anemoi framework, please ensure that your
changes include unit tests, updates to any affected dependencies and
documentation, and have been tested in a parallel setting (i.e., with
multiple GPUs). As a reviewer, you are also responsible for verifying
these aspects and requesting changes if they are not adequately
addressed. For guidelines about those please refer to
https://anemoi.readthedocs.io/en/latest/***

By opening this pull request, I affirm that all authors agree to the
[Contributor License
Agreement.](https://github.com/ecmwf/codex/blob/main/Legal/Contributor-License-Agreement.md)